Repository spoteditor/Spoteditor-Backend, pull requests merged in 2025-03, with the labels that each got.

#76 [TEST] 프론트엔드 테스트용 도메인 추가
  src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
Labels: 테스트🧪

#85 [fix] Spring과 Redis 컨테이너 연결 오류 문제
  docker-compose.yml
Labels: 🚨버그

#86 [fix] Spring과 Redis 컨테이너 연결 오류 문제2
  conf/slave.conf
  conf/slave1.conf
  conf/slave2.conf
  docker-compose.yml
Labels: 🚨버그

#80 [feat] 메인페이지 기능 추가
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
  src/main/java/com/spoteditor/backend/user/controller/UserController.java
  src/main/java/com/spoteditor/backend/user/controller/UserPlaceLogController.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserResponse.java
Labels: 기능 구현✨

#82 [fix] 로그에 장소에 이미지 등록시 장소 중복 등록 문제 해결
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
Labels: 🚨버그

#92 [fix] 비로그인 유저 서비스 사용을 위한 화이트리스트 추가
  src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogController.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogService.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
  src/main/java/com/spoteditor/backend/user/controller/UserPlaceLogController.java
Labels: 🚨버그, 서버 설정🛠️

#93 [TEST] 다른 사용자를 팔로우할 수 있다. - 리팩토링 및 테스트 코드 보완
  src/main/java/com/spoteditor/backend/follow/controller/dto/FollowResponse.java
  src/main/java/com/spoteditor/backend/follow/entity/Follow.java
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustomImpl.java
  src/main/java/com/spoteditor/backend/follow/service/facade/FollowFacade.java
  src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
  src/test/java/com/spoteditor/backend/config/QuerydslConfig.java
  src/test/java/com/spoteditor/backend/follow/entity/FollowTest.java
  src/test/java/com/spoteditor/backend/follow/repository/FollowRepositoryTest.java
  src/test/java/com/spoteditor/backend/follow/service/FollowServiceTest.java
Labels: 테스트 코드 작성✅, 리팩토링⚡️, 테스트🧪

#96 [fix] swagger 화이트리스트 추가
  src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
Labels: 🚨버그

#97 [CHORE] 수정된 Docker-Compose 반영
  docker-compose.yml
Labels: 서버 설정🛠️

#107 [chore] Docker compose시 spring container CREATED 상태에서 멈추는 버그 해결
  Dockerfile
  docker-compose.yml
  entrypoint.sh
Labels: 🚨버그, 서버 설정🛠️

#109 [chore] Docker compose Redis node 헬스체크 로직 변경
  docker-compose.yml
Labels: 🚨버그, 서버 설정🛠️

#101 [fix] 로그아웃 쿠키 MaxAge미적용 문제 해결
  src/main/java/com/spoteditor/backend/config/util/CookieUtils.java
Labels: 🚨버그

#104 [feat] API 정보 추가요청 반영
  src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
  src/main/java/com/spoteditor/backend/place/controller/dto/PlaceResponse.java
  src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryImpl.java
Labels: 기능 구현✨

#108 [TEST] 다른 사용자를 언팔로우할 수 있다. - 버그 개선 및 리팩토링
  src/main/java/com/spoteditor/backend/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/spoteditor/backend/bookmark/service/facade/BookmarkFacade.java
  src/main/java/com/spoteditor/backend/config/aop/AopForTransaction.java
  src/main/java/com/spoteditor/backend/config/aop/CustomSpringELParser.java
  src/main/java/com/spoteditor/backend/config/aop/DistributeLockAop.java
  src/main/java/com/spoteditor/backend/config/aop/DistributedLock.java
  src/main/java/com/spoteditor/backend/config/async/AsyncConfig.java
  src/main/java/com/spoteditor/backend/follow/controller/FollowApiController.java
  src/main/java/com/spoteditor/backend/follow/service/FollowService.java
  src/main/java/com/spoteditor/backend/follow/service/FollowServiceImpl.java
  src/main/java/com/spoteditor/backend/follow/service/facade/FollowFacade.java
  src/main/java/com/spoteditor/backend/notification/config/NotificationSubscriber.java
  src/main/java/com/spoteditor/backend/notification/controller/WebSocketHandler.java
  src/main/java/com/spoteditor/backend/notification/dto/NotificationDto.java
  src/main/java/com/spoteditor/backend/notification/dto/NotificationMessage.java
  src/main/java/com/spoteditor/backend/notification/event/NotificationEventDto.java
  src/main/java/com/spoteditor/backend/notification/handler/NotificationEventHandler.java
  src/main/java/com/spoteditor/backend/notification/service/NotificationService.java
  src/test/java/com/spoteditor/backend/follow/service/FollowServiceTest.java
Labels: 테스트 코드 작성✅, 🚨버그, 리팩토링⚡️, 테스트🧪

#114 [schema] flyway 태그 추가
  src/main/resources/db/migration/R__insert_tags.sql
Labels: 서버 설정🛠️

#117 [chore] Docker compose spring container 실행순서 변경
  docker-compose.yml
Labels: 🚨버그, 서버 설정🛠️

#112 [FEAT] 프론트엔드 측에서 요청한 API 추가 개발
  src/main/java/com/spoteditor/backend/bookmark/controller/BookmarkApiController.java
  src/main/java/com/spoteditor/backend/bookmark/controller/dto/BookmarkResponse.java
  src/main/java/com/spoteditor/backend/bookmark/repository/BookmarkRepository.java
  src/main/java/com/spoteditor/backend/bookmark/service/BookmarkService.java
  src/main/java/com/spoteditor/backend/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/spoteditor/backend/follow/controller/FollowApiController.java
  src/main/java/com/spoteditor/backend/follow/controller/dto/FollowResponse.java
  src/main/java/com/spoteditor/backend/follow/service/FollowServiceImpl.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogBookmarkController.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogBookmarkResponse.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogService.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
Labels: 기능 구현✨, 🚨버그, 리팩토링⚡️

#98 [feat] 로그 수정기능
  src/main/java/com/spoteditor/backend/config/swagger/PlaceLogApiDocument.java
  src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
  src/main/java/com/spoteditor/backend/image/service/PlaceImageService.java
  src/main/java/com/spoteditor/backend/image/service/PlaceImageServiceImpl.java
  src/main/java/com/spoteditor/backend/mapping/placelogplacemapping/repository/PlaceLogPlaceMappingRepositoryCustom.java
  src/main/java/com/spoteditor/backend/mapping/placelogplacemapping/repository/PlaceLogPlaceMappingRepositoryImpl.java
  src/main/java/com/spoteditor/backend/mapping/placelogtagmapping/repository/PlaceLogTagMappingRepositoryCustom.java
  src/main/java/com/spoteditor/backend/mapping/placelogtagmapping/repository/PlaceLogTagMappingRepositoryImpl.java
  src/main/java/com/spoteditor/backend/place/entity/Place.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogController.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogPlaceUpdateRequest.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogUpdateRequest.java
  src/main/java/com/spoteditor/backend/placelog/entity/PlaceLog.java
  src/main/java/com/spoteditor/backend/placelog/event/PlaceLogAfterCommitEvent.java
  src/main/java/com/spoteditor/backend/placelog/event/PlaceLogEventListener.java
  src/main/java/com/spoteditor/backend/placelog/event/PlaceLogRollbackEvent.java
  src/main/java/com/spoteditor/backend/placelog/event/dto/PlaceLogPlaceImage.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogService.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogPlaceUpdateCommand.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogUpdateCommand.java
Labels: 기능 구현✨, 문서📜

#120 [feat] PlaceLog 조회시 소유자 id 컬럼 추가
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogResponse.java
Labels: 기능 구현✨

#118 [feat] 로그 북마크 확인 기능
  src/main/java/com/spoteditor/backend/mapping/userplacelogmapping/repository/UserPlaceLogMappingRepositoryCustom.java
  src/main/java/com/spoteditor/backend/mapping/userplacelogmapping/repository/UserPlaceLogMappingRepositoryImpl.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogBookmarkController.java
Labels: 기능 구현✨

#122 [fix] PlaceRepository에 image join문 수정
  src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryImpl.java
Labels: 🚨버그

#124 [FIX] 팔로우/팔로워 내역 조회 시 DTO에서 제외된 필드로 인해 조회 시 500 오류 발생되는 문제
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustomImpl.java
Labels: 🚨버그

#126 [feat] 프론트 response 컬럼 추가
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustomImpl.java
  src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
  src/main/java/com/spoteditor/backend/user/controller/UserController.java
  src/main/java/com/spoteditor/backend/user/controller/dto/OtherUserResponse.java
  src/main/java/com/spoteditor/backend/user/service/UserService.java
  src/main/java/com/spoteditor/backend/user/service/UserServiceImpl.java
  src/main/java/com/spoteditor/backend/user/service/dto/OtherUserResult.java
Labels: 기능 구현✨

#131 [feat] 프론트 피드백내용 반영
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogController.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogListResponse.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogResponse.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
Labels: 기능 구현✨

#130 [fix] 프론트 피드백내용 반영
  src/main/java/com/spoteditor/backend/placelog/entity/PlaceLog.java
  src/main/java/com/spoteditor/backend/user/service/UserServiceImpl.java
Labels: 🚨버그

#133 [feat] 로그리스트 검색기능
  src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogSearchController.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
Labels: 기능 구현✨

#102 [test] 사용자 기능 테스트
  src/test/java/com/spoteditor/backend/config/TestJwtFilter.java
  src/test/java/com/spoteditor/backend/config/TestSecurityConfig.java
  src/test/java/com/spoteditor/backend/security/oauth/handler/OauthSuccessHandlerTest.java
  src/test/java/com/spoteditor/backend/user/controller/AuthControllerTest.java
  src/test/java/com/spoteditor/backend/user/controller/UserControllerTest.java
Labels: 테스트 코드 작성✅, 테스트🧪

#134 [FIX] 알림 API 버그 개선 내역
  .github/workflows/check.yml
  src/main/java/com/spoteditor/backend/config/swagger/NotificationApiDocument.java
  src/main/java/com/spoteditor/backend/follow/service/FollowServiceImpl.java
  src/main/java/com/spoteditor/backend/notification/controller/NotificationApiController.java
  src/main/java/com/spoteditor/backend/notification/controller/dto/NotificationListDto.java
  src/main/java/com/spoteditor/backend/notification/dto/NotificationMessage.java
  src/main/java/com/spoteditor/backend/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/spoteditor/backend/notification/repository/NotificationRepositoryCustomImpl.java
Labels: 🚨버그, 리팩토링⚡️

#136 [fix] Select구문에서 누락된 필드 추가
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
Labels: 🚨버그

#138 [feat] 로그 검색 sigungu -> bname 변경
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogSearchController.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
Labels: 기능 구현✨

#140 [docs] placeLogApi swagger 로그 수정기능 추가
  README.md
Labels: 문서📜

#142 [feat] 로그 리스트 조회시 최신순 정렬
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
Labels: 기능 구현✨

#146 [feat] 유저 이미지 변경 통합
  src/main/java/com/spoteditor/backend/image/event/S3ImageAfterCommitEvent.java
  src/main/java/com/spoteditor/backend/image/event/S3ImageEventListener.java
  src/main/java/com/spoteditor/backend/image/event/S3ImageRollbackEvent.java
  src/main/java/com/spoteditor/backend/image/event/dto/S3Image.java
  src/main/java/com/spoteditor/backend/image/service/PlaceImageService.java
  src/main/java/com/spoteditor/backend/image/service/PlaceImageServiceImpl.java
  src/main/java/com/spoteditor/backend/placelog/event/PlaceLogAfterCommitEvent.java
  src/main/java/com/spoteditor/backend/placelog/event/PlaceLogRollbackEvent.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
  src/main/java/com/spoteditor/backend/user/controller/dto/OtherUserResponse.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserBookmarkPlaceDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserBookmarkPlaceLogDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserPlaceLogDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserProfileImageDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserResponse.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserUpdateRequest.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserUpdateResponse.java
  src/main/java/com/spoteditor/backend/user/entity/User.java
  src/main/java/com/spoteditor/backend/user/service/UserServiceImpl.java
  src/main/java/com/spoteditor/backend/user/service/dto/OtherUserResult.java
  src/main/java/com/spoteditor/backend/user/service/dto/UserUpdateCommand.java
  src/main/resources/db/migration/V13__add_user_upload_image.sql
Labels: 기능 구현✨, 리팩토링⚡️

#150 [feat] CORS 허용 URL을 application.yml에서 리스트로 받아 설정
  src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
Labels: 기능 구현✨, 서버 설정🛠️
