Repository spoteditor/Spoteditor-Backend, pull requests merged in 2025-02, with the labels that each got.

#12 [Infra] 백엔드 인프라 아키텍처 구축
  .github/workflows/deploy.yml
  appspec.yml
  infra/Dockerfile
  infra/docker-compose.yml
  scripts/start.sh
Labels: 배포🏗️

#13 [Infra] 백엔드 인프라 아키텍처 구축(1차 수정)
  .github/workflows/deploy.yml
Labels: 배포🏗️, 🚨버그

#18 [fix] Flyway 마이그레이션 파일 수정
  src/main/resources/db/migration/mysql/V1__init.sql
  src/main/resources/db/migration/mysql/V2__add_oauth2_user_id_to_users.sql
  src/main/resources/db/migration/mysql/V3__remove_unique_constraint_from_place_name.sql
Labels: 🚨버그

#21 [feat] 회원 탈퇴, 로그아웃, 개인정보 수정
  src/main/java/com/spoteditor/backend/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
  src/main/java/com/spoteditor/backend/config/jwt/JwtUtils.java
  src/main/java/com/spoteditor/backend/config/oauth/dto/OauthAttributes.java
  src/main/java/com/spoteditor/backend/config/oauth/handler/OauthSuccessHandler.java
  src/main/java/com/spoteditor/backend/config/oauth/service/CustomOauthUserService.java
  src/main/java/com/spoteditor/backend/config/security/SecurityConfig.java
  src/main/java/com/spoteditor/backend/config/security/annotation/AdminOnly.java
  src/main/java/com/spoteditor/backend/config/security/annotation/AdminOnlyAspect.java
  src/main/java/com/spoteditor/backend/config/util/SecurityUtils.java
  src/main/java/com/spoteditor/backend/global/exception/TokenException.java
  src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
  src/main/java/com/spoteditor/backend/global/response/ErrorResponse.java
  src/main/java/com/spoteditor/backend/global/response/GlobalExceptionHandler.java
  src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/spoteditor/backend/place/service/PlaceServiceImpl.java
  src/main/java/com/spoteditor/backend/user/controller/AuthController.java
  src/main/java/com/spoteditor/backend/user/controller/UserController.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserBookmarkPlaceDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserBookmarkPlaceLogDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserPlaceLogDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserResponse.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserUpdateRequest.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserUpdateResponse.java
  src/main/java/com/spoteditor/backend/user/entity/OauthProvider.java
  src/main/java/com/spoteditor/backend/user/entity/User.java
  src/main/java/com/spoteditor/backend/user/entity/UserRole.java
  src/main/java/com/spoteditor/backend/user/repository/UserRepository.java
  src/main/java/com/spoteditor/backend/user/service/UserService.java
  src/main/java/com/spoteditor/backend/user/service/UserServiceImpl.java
  src/main/java/com/spoteditor/backend/user/service/UserTokenService.java
  src/main/java/com/spoteditor/backend/user/service/dto/UserResult.java
  src/main/java/com/spoteditor/backend/user/service/dto/UserUpdateCommand.java
  src/main/java/com/spoteditor/backend/user/service/dto/UserUpdateResult.java
  src/test/java/com/spoteditor/backend/domain/user/entity/value/OauthProviderTest.java
  src/test/java/com/spoteditor/backend/security/oauth/dto/OauthAttributesTest.java
  src/test/java/com/spoteditor/backend/security/oauth/dto/OauthAttributesUserMapperTest.java
  src/test/java/com/spoteditor/backend/security/oauth/service/OauthUserResolverTest.java
Labels: 기능 구현✨

#22 [feat] 로그 도메인 CRUD 기능 추가
  src/main/java/com/spoteditor/backend/global/exception/PlaceLogException.java
  src/main/java/com/spoteditor/backend/global/exception/TagException.java
  src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
  src/main/java/com/spoteditor/backend/mapping/placelogplacemapping/entity/PlaceLogPlaceMapping.java
  src/main/java/com/spoteditor/backend/mapping/placelogplacemapping/entity/PlaceLogPlaceMappingId.java
  src/main/java/com/spoteditor/backend/mapping/placelogplacemapping/repository/PlaceLogPlaceMappingRepository.java
  src/main/java/com/spoteditor/backend/mapping/placelogplacemapping/repository/PlaceLogPlaceMappingRepositoryCustom.java
  src/main/java/com/spoteditor/backend/mapping/placelogplacemapping/repository/PlaceLogPlaceMappingRepositoryImpl.java
  src/main/java/com/spoteditor/backend/mapping/placelogtagmapping/entity/PlaceLogTagMapping.java
  src/main/java/com/spoteditor/backend/mapping/placelogtagmapping/entity/PlaceLogTagMappingId.java
  src/main/java/com/spoteditor/backend/mapping/placelogtagmapping/repository/PlaceLogTagMappingRepository.java
  src/main/java/com/spoteditor/backend/mapping/placelogtagmapping/repository/PlaceLogTagMappingRepositoryCustom.java
  src/main/java/com/spoteditor/backend/mapping/placelogtagmapping/repository/PlaceLogTagMappingRepositoryImpl.java
  src/main/java/com/spoteditor/backend/mapping/userplacelogmapping/entity/UserPlaceLogMapping.java
  src/main/java/com/spoteditor/backend/mapping/userplacelogmapping/repository/UserPlaceLogMappingRepository.java
  src/main/java/com/spoteditor/backend/mapping/userplacelogmapping/repository/UserPlaceLogMappingRepositoryCustom.java
  src/main/java/com/spoteditor/backend/mapping/userplacelogmapping/repository/UserPlaceLogMappingRepositoryImpl.java
  src/main/java/com/spoteditor/backend/place/controller/dto/PlaceResponse.java
  src/main/java/com/spoteditor/backend/place/entity/Place.java
  src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogController.java
  src/main/java/com/spoteditor/backend/placelog/controller/TempPlaceLogController.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogPlaceRegisterResponse.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogPlaceRequest.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogRegisterResponse.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogResponse.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/TempPlaceLogRegisterRequest.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/TempPlaceLogRegisterResponse.java
  src/main/java/com/spoteditor/backend/placelog/entity/PlaceLog.java
  src/main/java/com/spoteditor/backend/placelog/entity/PlaceLogStatus.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepository.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogService.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogPlaceCommand.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogRegisterCommand.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogRegisterResult.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogResult.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/TempPlaceLogPlaceResult.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/TempPlaceLogRegisterCommand.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/TempPlaceLogRegisterResult.java
  src/main/java/com/spoteditor/backend/tag/controller/dto/TagResponse.java
  src/main/java/com/spoteditor/backend/tag/entity/Tag.java
  src/main/java/com/spoteditor/backend/tag/entity/TagCategory.java
  src/main/java/com/spoteditor/backend/tag/repository/TagRepository.java
  src/main/java/com/spoteditor/backend/tag/repository/TagRepositoryCustom.java
  src/main/java/com/spoteditor/backend/tag/repository/TagRepositoryImpl.java
  src/main/resources/db/migration/mysql/V4__add_place_log_table.sql
  src/main/resources/db/migration/mysql/V5__add_user_place_log.sql
  src/main/resources/db/migration/mysql/V6__add_place_log_place.sql
  src/main/resources/db/migration/mysql/V7__add_place_log_tag.sql
Labels: 기능 구현✨

#19 [feat] 팔로우 도메인 기능 추가
  build.gradle
  src/main/java/com/spoteditor/backend/bookmark/controller/BookmarkApiController.java
  src/main/java/com/spoteditor/backend/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/spoteditor/backend/config/redis/RedisConfiguration.java
  src/main/java/com/spoteditor/backend/follow/controller/FollowApiController.java
  src/main/java/com/spoteditor/backend/follow/controller/dto/FollowRequest.java
  src/main/java/com/spoteditor/backend/follow/controller/dto/FollowResponse.java
  src/main/java/com/spoteditor/backend/follow/entity/Follow.java
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepository.java
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustomImpl.java
  src/main/java/com/spoteditor/backend/follow/service/FollowService.java
  src/main/java/com/spoteditor/backend/follow/service/FollowServiceImpl.java
  src/main/java/com/spoteditor/backend/global/exception/FollowException.java
  src/main/java/com/spoteditor/backend/global/exception/NotificationException.java
  src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
  src/main/java/com/spoteditor/backend/global/response/GlobalExceptionHandler.java
  src/main/java/com/spoteditor/backend/image/controller/PlaceImageApiController.java
  src/main/java/com/spoteditor/backend/image/service/PlaceImageServiceImpl.java
  src/main/java/com/spoteditor/backend/notification/config/JsonConverter.java
  src/main/java/com/spoteditor/backend/notification/config/NotificationPublisher.java
  src/main/java/com/spoteditor/backend/notification/config/NotificationSubscriber.java
  src/main/java/com/spoteditor/backend/notification/config/RabbitMqConfiguration.java
  src/main/java/com/spoteditor/backend/notification/config/WebSocketConfiguration.java
  src/main/java/com/spoteditor/backend/notification/controller/NotificationApiController.java
  src/main/java/com/spoteditor/backend/notification/controller/WebSocketHandler.java
  src/main/java/com/spoteditor/backend/notification/controller/dto/NotificationListDto.java
  src/main/java/com/spoteditor/backend/notification/dto/NotificationDto.java
  src/main/java/com/spoteditor/backend/notification/entity/Notification.java
  src/main/java/com/spoteditor/backend/notification/entity/NotificationType.java
  src/main/java/com/spoteditor/backend/notification/repository/NotificationRepository.java
  src/main/java/com/spoteditor/backend/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/spoteditor/backend/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/java/com/spoteditor/backend/notification/service/NotificationService.java
  src/main/java/com/spoteditor/backend/place/controller/PlaceApiController.java
  src/main/java/com/spoteditor/backend/place/service/PlaceServiceImpl.java
  src/main/java/com/spoteditor/backend/user/repository/UserRepository.java
  src/test/java/com/spoteditor/backend/config/RedisConfiguration.java
Labels: 기능 구현✨, 🚨버그

#25 [fix] DB 형상 관리 오류로 인한 버그 수정
  docker-compose.yml
  src/main/java/com/spoteditor/backend/follow/entity/Follow.java
  src/main/java/com/spoteditor/backend/notification/entity/Notification.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__add_place_log_table.sql
  src/main/resources/db/migration/V3__add_user_place_log.sql
  src/main/resources/db/migration/V4__add_place_log_place.sql
  src/main/resources/db/migration/V5__add_place_log_tag.sql
  src/main/resources/db/migration/V6__add_notification.sql
  src/main/resources/db/migration/V7__add_follow.sql
Labels: 🚨버그, ⚡️개선

#26 [fix] V2 ~ V5 테이블 대소문자 불일치 오류
  src/main/resources/db/migration/V2__add_place_log_table.sql
  src/main/resources/db/migration/V3__add_user_place_log.sql
  src/main/resources/db/migration/V4__add_place_log_place.sql
  src/main/resources/db/migration/V5__add_place_log_tag.sql
Labels: 🚨버그, ⚡️개선

#29 [fix] flyway BaseEntity 누락된 부분 수정
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__add_place_log_table.sql
  src/main/resources/db/migration/V3__add_user_place_log.sql
  src/main/resources/db/migration/V4__add_place_log_place.sql
  src/main/resources/db/migration/V5__add_place_log_tag.sql
  src/main/resources/db/migration/V6__add_notification.sql
Labels: 🚨버그

#52 [fix] JwtFilter 에서 Exception 덮어씌워지는 오류 해결
  src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
  src/main/java/com/spoteditor/backend/config/jwt/JwtUtils.java
  src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
  src/main/java/com/spoteditor/backend/global/response/GlobalExceptionHandler.java
  src/main/java/com/spoteditor/backend/user/service/UserTokenService.java
Labels: 🚨버그

#53 [docs] Swagger API 명세서 작업
  src/main/java/com/spoteditor/backend/bookmark/controller/BookmarkApiController.java
  src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
  src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
  src/main/java/com/spoteditor/backend/config/swagger/BookmarkApiDocument.java
  src/main/java/com/spoteditor/backend/config/swagger/FollowApiDocument.java
  src/main/java/com/spoteditor/backend/config/swagger/NotificationApiDocument.java
  src/main/java/com/spoteditor/backend/config/swagger/PlaceApiDocument.java
  src/main/java/com/spoteditor/backend/config/swagger/PlaceImageApiDocument.java
  src/main/java/com/spoteditor/backend/config/swagger/SwaggerConfiguration.java
  src/main/java/com/spoteditor/backend/follow/controller/FollowApiController.java
  src/main/java/com/spoteditor/backend/image/controller/PlaceImageApiController.java
  src/main/java/com/spoteditor/backend/notification/controller/NotificationApiController.java
  src/main/java/com/spoteditor/backend/place/controller/PlaceApiController.java
Labels: 문서📜

#56 [docs] Swagger API 명세서 작업
  src/main/java/com/spoteditor/backend/config/swagger/PlaceLogApiDocument.java
  src/main/java/com/spoteditor/backend/config/swagger/TempPlaceLogApiDocument.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogController.java
  src/main/java/com/spoteditor/backend/placelog/controller/TempPlaceLogController.java
Labels: 문서📜

#57 [fix] setSecure 속성 false로 변경
  src/main/java/com/spoteditor/backend/config/util/CookieUtils.java
Labels: 🚨버그

#61 [fix] 카카오 로그인 성공시 redirect주소 application.yml 설정 가능하게 변경
  src/main/java/com/spoteditor/backend/config/oauth/handler/OauthSuccessHandler.java
Labels: 서버 설정🛠️

#62 [feat] PlaceLog 기능수정
  src/main/java/com/spoteditor/backend/config/swagger/PlaceLogApiDocument.java
  src/main/java/com/spoteditor/backend/config/swagger/PlaceLogBookmarkApiDocument.java
  src/main/java/com/spoteditor/backend/config/swagger/TempPlaceLogApiDocument.java
  src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
  src/main/java/com/spoteditor/backend/global/response/GlobalExceptionHandler.java
  src/main/java/com/spoteditor/backend/image/service/PlaceImageService.java
  src/main/java/com/spoteditor/backend/image/service/PlaceImageServiceImpl.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogBookmarkController.java
  src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogController.java
  src/main/java/com/spoteditor/backend/placelog/controller/TempPlaceLogController.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogListResponse.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogPlaceRegisterRequest.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogPlaceRegisterResponse.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogPlaceRequest.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogRegisterRequest.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogRegisterResponse.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogResponse.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/TempPlaceLogRegisterRequest.java
  src/main/java/com/spoteditor/backend/placelog/controller/dto/TempPlaceLogRegisterResponse.java
  src/main/java/com/spoteditor/backend/placelog/entity/PlaceLog.java
  src/main/java/com/spoteditor/backend/placelog/entity/PlaceLogStatus.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogBookmarkService.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogBookmarkServiceImpl.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogService.java
  src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogRegisterCommand.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogRegisterResult.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/PlaceLogResult.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/TempPlaceLogPlaceResult.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/TempPlaceLogRegisterCommand.java
  src/main/java/com/spoteditor/backend/placelog/service/dto/TempPlaceLogRegisterResult.java
  src/main/java/com/spoteditor/backend/tag/controller/dto/TagResponse.java
  src/main/java/com/spoteditor/backend/tag/dto/TagDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserBookmarkPlaceLogDto.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserPlaceLogDto.java
  src/main/resources/db/migration/V11__alter_place_log_image.sql
  src/main/resources/db/migration/V12__alter_place_log.sql
Labels: 기능 구현✨, 리팩토링⚡️, 문서📜

#64 [test] OauthProvider 지원하는 Provider, 지원하지 않는 Provider 예외 테스트코드 추가
  src/test/java/com/spoteditor/backend/domain/user/entity/value/OauthProviderTest.java
Labels: 테스트 코드 작성✅, 테스트🧪

#67 [feat] HTTPS 적용을 위한 healthCheck 추가
  src/main/java/com/spoteditor/backend/config/util/CookieUtils.java
  src/main/java/com/spoteditor/backend/global/health/HealthCheckController.java
Labels: 기능 구현✨

#70 [feat] 쿠키 저장을 위한 HTTPS 적용
  src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
  src/main/java/com/spoteditor/backend/config/security/SecurityConfig.java
Labels: 🚨버그

#73 [test] JwtUtils 테스트
  src/test/java/com/spoteditor/backend/config/jwt/JwtUtilsTest.java
  src/test/java/com/spoteditor/backend/security/jwt/JwtUtilTest.java
Labels: 테스트🧪

#72 [feat] 유저 메인페이지 기능
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustomImpl.java
  src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
  src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
  src/main/java/com/spoteditor/backend/user/controller/UserPlaceLogController.java
  src/main/java/com/spoteditor/backend/user/controller/dto/UserResponse.java
  src/main/java/com/spoteditor/backend/user/service/UserServiceImpl.java
  src/main/java/com/spoteditor/backend/user/service/dto/UserResult.java
Labels: 기능 구현✨
